### ISSUE TITLE
Assertion failed: f != 0 && "could not open rom file!", at: /usr/local/src/CppOpenGLWebAssemblyCMake/galaga/GalagaRoms.cpp,17,LoadFile

### ISSUE THREAD

**Issue by popomen** [lukka/CppOpenGLWebAssemblyCMake#8] opened 2020-05-15 03:02 UTC
![image](https://user-images.githubusercontent.com/59364722/82006913-77aac900-969b-11ea-91f7-46410cc24f2b.png)

**Comment by lukka** [comment] 2020-05-15 03:08
@popomen  this is a duplicate of this one:
https://github.com/lukka/CppOpenGLWebAssemblyCMake/issues/2

**Closed by lukka** 2020-05-15 03:08 UTC
